server:
  port: 8080
spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    bus:
      enabled: false
      id: config-service
    stream:
      kafka:
        binder:
          brokers: kafka1:19092
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: ui-service
          uri: lb://ui-service
          predicates:
            - Path=/ui-service/**
          filters:
            - StripPrefix=1
        - id: keycloak
          uri: '${spring.security.oauth2.client.provider-uri}/'
          predicates:
            - Path=/auth/**
          filters:
            - AddRequestHeader=X-Forwarded-For, ${spring.security.oauth2.client.base-uri}
            - AddRequestHeader=X-Forwarded-Proto, http
  security:
    oauth2:
      client:
        base-uri: http://localhost:8080
        provider-uri: http://keycloak:9090
        logout-uri: '${spring.security.oauth2.client.base-uri}/auth/realms/compaj/protocol/openid-connect/logout?redirect_uri=${spring.security.oauth2.client.base-uri}'
        provider:
          keycloak:
            issuer-uri: '${spring.security.oauth2.client.provider-uri}/auth/realms/compaj'
            authorization-uri: '${spring.security.oauth2.client.base-uri}/auth/realms/compaj/protocol/openid-connect/auth'
            user-info-uri: '${spring.security.oauth2.client.base-uri}/auth/realms/compaj/protocol/openid-connect/userinfo'
            jwk-set-uri: '${spring.security.oauth2.client.provider-uri}/auth/realms/compaj/protocol/openid-connect/certs'
            user-name-attribute: preferred_username
        registration:
          keycloak-spring-gateway-client:
            provider: keycloak
            client-id: compaj-cloud-gateway
            client-secret: ifhsRmb6F2EyYubpTsPkXtiiOcPWIzf4
            authorization-grant-type: authorization_code
  session:
    store-type: redis
  redis:
    host: redis-session
    port: 6379
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    hostname: gateway-service

logging:
  level:
    org:
      springframework:
        security: TRACE