version: '3'

services:
  gateway-service:
    image: 'gateway-service:latest'
    depends_on:
      - config-service
      - discovery-service
    networks:
      - providers_config
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"

networks:
  providers_config:
    external:
      name: providers_config